config/routes.rb
Rails.application.routes.draw do
  root :to => 'sessions#index'
  match '/login' => 'sessions#create', :as => :login, :via => :post
  match '/logout' => 'sessions#destroy', :as => :logout, :via => :delete

  resources :templates
  resources :password_resets, only: [:new, :create, :show, :update]
  resources :boards do collection { post :mark } end
  resources :reports, only: [:index, :show]
  resources :bugs, only: :create
  resources :messages, except: :edit do
    collection { post :mark }
  end
  resources :replies, except: [:index, :new] do
    member { get :history }
  end
  resources :posts do
    member { get :history }
    collection do
      post :mark
      get :search
      get :owed
      get :unread
    end
  end
  resources :characters do
    member do
      post :icon
    end
    collection { get :facecasts }
  end
  resources :icons, except: [:index, :new, :create] do
    member do
      post :avatar
    end
    collection do
      delete :delete_multiple
    end
  end
  resources :users do
    resources :characters, only: :index
    resources :templates, only: :index
    resources :galleries, only: [:index, :show]
    collection do
      post :username
    end
    member do
      post :character
      put :password
    end
  end
  resources :galleries do
    member do
      get :add
      post :icon
    end
  end
end

app/views/templates/_single.haml
%table
  %tr
    %th.subber.padding-10{colspan: 6}
      = title
      - if template.user_id == current_user.try(:id)
        = link_to new_character_path(template_id: template.id) do
          .link-box.green + New Instance
        = link_to edit_template_path(template) do
          .link-box.blue
            = image_tag '/images/pencil.png'
            Edit Template
        = link_to template_path(template), :method => :delete, confirm: 'Are you sure you want to delete this template?' do
          .link-box.red x Delete Template
      - if page_view == 'list'
        - @template = template
        = render partial: 'characters/list_view'
      - else
        - @characters = template.characters
        = render partial: 'characters/icon_view'

app/views/templates/edit.haml
= form_for @template, :url => template_path(@template), :method => :put do |f|
  %table.form-table
    %tr
      %th.centered{colspan: 2} Edit Template
    %tr
      %th.sub Template Name
      %td.even= f.text_field :name, placeholder: "Template Name", class: 'text'
    %tr
      %th.subber{colspan: 2}= submit_tag "Save", class: 'button'

app/views/templates/index.haml
- content_for :breadcrumbs do
  - if @user.id == current_user.try(:id)
    = link_to "Characters", characters_path
    &raquo;
    %b Templates
  - else
    = link_to "#{@user.username}'s Characters", user_characters_path(@user)
    &raquo;
    %b #{@user.username}'s Templates

%table
  %tr
    %th.padding-10
      - if @user.id == current_user.try(:id)
        Your Templates
        = link_to new_template_path do
          .link-box.green + New Template
      - else
        = @user.username + "'s Templates"

- @templates.includes(:characters).order('name asc').each do |template|
  = render partial: 'single', locals: {title: link_to(template.name, template_path(template)), template: template}

app/views/templates/new.haml
= form_for @template, :url => templates_path, :method => :post do |f|
  %table.form-table
    %tr
      %th.centered{colspan: 2} New Template
    %tr
      %th.sub Template Name
      %td.even= f.text_field :name, placeholder: "Template Name", class: 'text'
    %tr
      %th.subber{colspan: 2}= submit_tag "Create", class: 'button'

app/views/templates/show.haml
- content_for :breadcrumbs do
  - if @template.user_id == current_user.try(:id)
    = link_to "Characters", characters_path
    &raquo;
    = link_to "Templates", templates_path
  - else
    = link_to "#{@template.user.username}'s Characters", user_characters_path(@template.user)
    &raquo;
    = link_to "#{@template.user.username}'s Templates", user_templates_path(@template.user)
  &raquo;
  %b= @template.name

%table
  %tr
    %th{colspan: 6}
      Template: #{@template.name}
      - if @template.user_id == current_user.try(:id)
        = link_to new_character_path(template_id: @template.id) do
          .link-box.green + New Instance
        = link_to edit_template_path(@template) do
          .link-box.blue
            = image_tag '/images/pencil.png'
            Edit Template
        = link_to template_path(@template), :method => :delete, confirm: 'Are you sure you want to delete this template?' do
          .link-box.red x Delete Template
      = link_to url_for(view: 'icons') do
        .view-button{class: (:selected unless page_view == 'list')}
          = image_tag '/images/grid.png', class:'icon-view', alt: ''
          Icons
      = link_to url_for(view: 'list') do
        .view-button{class: (:selected if page_view == 'list')}
          = image_tag '/images/list.png', class:'list-view', alt: ''
          List
  - if page_view == 'list'
    = render partial: 'characters/list_view'
  - else
    = render partial: 'characters/icon_view'