config/routes.rb
Rails.application.routes.draw do
  root :to => 'sessions#index'
  match '/login' => 'sessions#create', :as => :login, :via => :post
  match '/logout' => 'sessions#destroy', :as => :logout, :via => :delete

  resources :templates
  resources :password_resets, only: [:new, :create, :show, :update]
  resources :boards do collection { post :mark } end
  resources :reports, only: [:index, :show]
  resources :bugs, only: :create
  resources :messages, except: :edit do
    collection { post :mark }
  end
  resources :replies, except: [:index, :new] do
    member { get :history }
  end
  resources :posts do
    member { get :history }
    collection do
      post :mark
      get :search
      get :owed
      get :unread
    end
  end
  resources :characters do
    member do
      post :icon
    end
    collection { get :facecasts }
  end
  resources :icons, except: [:index, :new, :create] do
    member do
      post :avatar
    end
    collection do
      delete :delete_multiple
    end
  end
  resources :users do
    resources :characters, only: :index
    resources :templates, only: :index
    resources :galleries, only: [:index, :show]
    collection do
      post :username
    end
    member do
      post :character
      put :password
    end
  end
  resources :galleries do
    member do
      get :add
      post :icon
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  MIN_USERNAME_LEN = 3
  MAX_USERNAME_LEN = 80

  attr_accessor :password, :password_confirmation
  attr_protected :crypted
  attr_writer :validate_password

  has_many :icons
  has_many :characters
  has_many :galleries
  has_many :character_groups
  has_many :templates
  has_many :sent_messages, :class_name => Message, :foreign_key => 'sender_id'
  has_many :messages, :foreign_key => 'recipient_id'
  has_many :password_resets
  belongs_to :avatar, :class_name => Icon
  belongs_to :active_character, :class_name => Character

  validates_presence_of :username, :crypted
  validates_uniqueness_of :username
  validates_uniqueness_of :email, allow_blank: true
  validates_length_of :username, :in => MIN_USERNAME_LEN..MAX_USERNAME_LEN, :allow_blank => true
  validates_length_of :moiety, in: 3..6, allow_blank: true
  validates_length_of :password, :in => 6..25, if: :validate_password?
  validates_confirmation_of :password, if: :validate_password?
  validates_presence_of :password, :password_confirmation, if: :validate_password?

  before_validation :encrypt_password
  after_save :clear_password

  nilify_blanks

  def authenticate(password)
    crypted == crypted_password(password)
  end

  def gon_attributes
    { 
      :username => username, 
      :active_character_id => active_character_id, 
      :avatar => { :id => avatar.try(:id), :url => avatar.try(:url) },
    }
  end

  def writes_in?(continuity)
    continuity.open_to?(self)
  end

  def admin?
    id == 1
  end

  def galleryless_icons
    icons.where(has_gallery: false)
  end

  def default_view
    super || 'icon'
  end

  private

  def encrypt_password
    self.crypted = crypted_password(password) if password.present?
  end

  def crypted_password(unencrypted)
    crypted = "Adding #{salt} to #{unencrypted}"
    17.times { crypted = Digest::SHA1.hexdigest(crypted) }
    crypted
  end

  def salt
    "1d0e9f00dc7#{username.to_s.downcase}dda7264ec524b051e434f4dda9ecfef8891004efe56fbff6a0"
  end

  def clear_password
    self.password = nil
    self.password_confirmation = nil
  end

  def validate_password?
    !!@validate_password
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signup_prep, :only => :new
  before_filter :login_required, :except => [:index, :show, :new, :create, :username]

  def index
  end

  def show
    unless @user = User.find_by_id(params[:id])
      flash[:error] = "User could not be found."
      redirect_to users_path and return
    end
    post_ids = Post.where(user_id: @user.id).order('updated_at desc').select(:id).map(&:id)
    reply_ids = Reply.where(user_id: @user.id).group(:post_id).select("post_id, max(updated_at)").map(&:post_id)
    ids = (post_ids + reply_ids).uniq
    @posts = Post.where(id: ids).order('tagged_at desc').includes(:board, :user, :last_user).paginate(per_page: 25, page: page)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.validate_password = true
    
    if params[:secret] != "ALLHAILTHECOIN"
      flash.now[:error] = "This is in beta. Please come back later."
      render :action => "new" and return
    end

    if @user.save
      flash[:success] = "User created! You have been logged in."
      session[:user_id] = @user.id
      @current_user = @user
      redirect_to root_url
    else
      signup_prep
      flash.now[:error] = {}
      flash.now[:error][:message] = "There was a problem completing your sign up."
      flash.now[:error][:array] = @user.errors.full_messages
      render :action => "new"
    end
  end

  def edit
    use_javascript('users')
  end

  def update
    params[:user][:per_page] = -1 if params[:user].try(:[], :per_page) == 'all'
    if current_user.update_attributes(params[:user])
      flash[:success] = "Changes saved successfully."
    else
      flash[:error] = "There was a problem with your changes."
    end
    redirect_to edit_user_path(current_user)
  end

  def password
    unless current_user.authenticate(params[:old_password])
      flash.now[:error] = "Incorrect password entered."
      render action: :edit and return
    end
    
    current_user.validate_password = true
    if current_user.update_attributes(params[:user])
      flash[:success] = "Changes saved successfully."
      redirect_to edit_user_path(current_user)
    else
      flash.now[:error] = {}
      flash.now[:error][:message] = "There was a problem with your changes."
      flash.now[:error][:array] = current_user.errors.full_messages
      render action: :edit
    end
  end

  def username
    render :json => { :error => "No username provided." } and return unless params[:username]
    render :json => { :username_free => User.find_by_username(params[:username]).nil? }
  end

  def character
    character = Character.find_by_id(params[:character_id])
    render :json => CharacterPresenter.new(character)
  end

  private

  def signup_prep
    use_javascript('users')
    gon.max = User::MAX_USERNAME_LEN
    gon.min = User::MIN_USERNAME_LEN
  end
end

app/views/users/edit.haml
= form_for current_user, :url => user_path(current_user), :method => :put do |f|
  %table.form-table
    %tr
      %th.centered{colspan: 2} Account Settings
    %tr
      %th.sub Username
      %td.even= f.text_field :username, placeholder: "Username", class: 'text'
    %tr
      %th.sub Email
      %td.odd= f.text_field :email, placeholder: "Email address", class: 'text'
    %tr
      %th.sub Notifications
      %td.even
        = f.check_box :email_notifications, class: 'width-15 vmid'
        Email about new tags
    %tr
      %th.sub Paging
      %td.odd= f.select(:per_page, per_page_options(current_user.per_page))
    %tr
      %th.sub Time zone
      %td.even= f.select(:timezone, timezone_options(current_user.timezone))
    %tr
      %th.sub Split icon picker
      %td.odd
        = f.check_box :icon_picker_grouping, class: 'width-15 vmid'
        Group the icon picker by gallery
    %tr
      %th.sub Default View
      %td.even= f.select(:default_view, options_for_select({Icon: 'icon', List: 'list'}, current_user.default_view))
    %tr
      %th.sub Default Editor
      %td.odd= f.select(:default_editor, options_for_select({'Rich Text' => 'rtf', HTML: 'html'}, current_user.default_editor))
    %tr
      %th.sub Moiety Hex
      %td.even
        \#
        = f.text_field :moiety, placeholder: "Hex code", class: 'text', style: 'width: 80px;', maxlength: 6
    %tr
      %th.sub Moiety Name
      %td.even= f.text_field :moiety_name, placeholder: "Moiety", class: 'text'
    %tr
      %th.sub Layout
      %td.odd= f.select :layout, layout_options(current_user.layout)
    %tr
      %th.centered.subber{colspan: 2}= submit_tag "Save", class: 'button'

%br
= form_for current_user, :url => password_user_path(current_user), :method => :put do |f|
  %table.form-table
    %tr
      %th.centered{colspan: 2} Change Password
    %tr
      %th.sub Old
      %td.even= password_field_tag :old_password, params[:old_password], :placeholder => "Old Password", :class => 'text'
    %tr
      %th.sub New
      %td.odd= f.password_field :password, :placeholder => "New Password", :class => 'text', :value => (params[:user]||{})[:password]
    %tr
      %th.sub Confirm
      %td.even= f.password_field :password_confirmation, :placeholder => "Confirm Password", :class => 'text', :value => (params[:user]||{})[:password_confirmation]
    %tr
      %th.centered.subber{colspan: 2}= submit_tag "Save", class: 'button'

app/views/users/index.haml
%table
  %thead
    %tr
      %th{colspan: 3} Glowficcers
    %tr
      %th.sub Name
      %th.width-70.sub.centered Moiety
      %th.sub Date Joined
  %tbody
    - User.order('username asc').each do |user|
      %tr
        - klass = cycle('even','odd')
        %td.padding-10.username{class: klass}= link_to user.username, user_path(user)
        %td.padding-10.user-moiety.centered.width-70{class: klass}= color_block(user)
        %td.padding-10.user-date{class: klass}= pretty_time(user.created_at)

app/views/users/new.haml
= form_for @user, :url => users_path, :method => :post do |f|
  %table#signup.centered
    %tr
      %th.centered{:colspan=>3} Sign Up
    %tr#username
      %td.alert
      %td.entry= f.text_field :username, :placeholder => "Username", :class => 'text'
      %td.messages
    %tr#email
      %td.alert
      %td.entry= f.text_field :email, placeholder: "Email address (optional)", class: 'text'
      %td.messages
    %tr#password
      %td.alert
      %td.entry= f.password_field :password, :placeholder => "Password", :class => 'text', :value => (params[:user]||{})[:password]
      %td.messages
    %tr#conf
      %td.alert
      %td.entry= f.password_field :password_confirmation, :placeholder => "Confirm Password", :class => 'text', :value => (params[:user]||{})[:password_confirmation]
      %td.messages
    %tr#secret
      %td.alert
      %td.entry= text_field_tag :secret, params[:secret], :placeholder => "Secret", :class => 'text'
      %td.messages
    %tr
      %td.centered{colspan: 3}= submit_tag "Sign up", class: 'button'
    %tr
      %td
        .width-15
      %td
      %td
        .width-15

app/views/users/show.haml
- if @user.avatar
  .user-avatar
    = link_to icon_path(@user.avatar) do
      = icon_tag @user.avatar
%b.username= @user.username
%br
- if @user.moiety
  %b Moiety:
  = color_block(@user)
  - if @user.moiety_name.present?
    %span{style: 'font-weight: bold; color:#' + @user.moiety}= @user.moiety_name
  %br
= link_to "#{@user.username}'s characters", user_characters_path(@user), class: 'user-characters'
%br
= link_to "#{@user.username}'s templates", user_templates_path(@user), class: 'user-templates'
%br
= link_to "#{@user.username}'s galleries", user_galleries_path(@user), class: 'user-galleries'
%br
%br
- content_for :posts_title do
  #{@user.username}'s Recent Posts
= render partial: 'posts/list', locals: {posts: @posts, path: :user_path}