config/routes.rb
Rails.application.routes.draw do
  root :to => 'sessions#index'
  match '/login' => 'sessions#create', :as => :login, :via => :post
  match '/logout' => 'sessions#destroy', :as => :logout, :via => :delete

  resources :templates
  resources :password_resets, only: [:new, :create, :show, :update]
  resources :boards do collection { post :mark } end
  resources :reports, only: [:index, :show]
  resources :bugs, only: :create
  resources :messages, except: :edit do
    collection { post :mark }
  end
  resources :replies, except: [:index, :new] do
    member { get :history }
  end
  resources :posts do
    member { get :history }
    collection do
      post :mark
      get :search
      get :owed
      get :unread
    end
  end
  resources :characters do
    member do
      post :icon
    end
    collection { get :facecasts }
  end
  resources :icons, except: [:index, :new, :create] do
    member do
      post :avatar
    end
    collection do
      delete :delete_multiple
    end
  end
  resources :users do
    resources :characters, only: :index
    resources :templates, only: :index
    resources :galleries, only: [:index, :show]
    collection do
      post :username
    end
    member do
      post :character
      put :password
    end
  end
  resources :galleries do
    member do
      get :add
      post :icon
    end
  end
end

app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :user
  belongs_to :template
  belongs_to :gallery
  belongs_to :default_icon, class_name: Icon
  belongs_to :character_group
  has_many :replies
  has_many :posts
  has_and_belongs_to_many :galleries

  validates_presence_of :name, :user
  validate :valid_template, :valid_group

  after_save :update_galleries

  attr_accessor :new_template_name, :group_name, :gallery_ids

  nilify_blanks

  def icon
    @icon ||= default_icon || galleries.detect(&:default_icon).try(:default_icon)
  end

  def recent_posts(limit=25, page=1)
    return @recent unless @recent.nil?
    reply_ids =  replies.group(:post_id).select(:post_id).map(&:post_id)
    post_ids = posts.select(:id).map(&:id)
    @recent ||= Post.where(id: (post_ids + reply_ids).uniq).order('tagged_at desc').paginate(per_page: limit, page: page)
  end

  def selector_name
    [name, template_name, screenname].compact.join(' | ')
  end

  private

  def valid_template
    return unless template_id == 0
    @template = Template.new(user: user, name: new_template_name)
    return if @template.valid?
    @template.errors.messages.each do |k, v|
      v.each { |val| errors.add('template '+k.to_s, val) }
    end
  end

  def valid_group
    return unless character_group_id == 0
    @group = CharacterGroup.new(user: user, name: group_name)
    return if @group.valid?
    @group.errors.messages.each do |k, v|
      v.each { |val| errors.add('group '+k.to_s, val) }
    end
  end

  def update_galleries
    return unless gallery_ids

    updated_ids = (gallery_ids - [""]).map(&:to_i)
    existing_ids = galleries.map(&:id)

    CharactersGallery.where(character_id: id, gallery_id: (existing_ids - updated_ids)).destroy_all
    (updated_ids - existing_ids).each do |new_id|
      CharactersGallery.create(character_id: id, gallery_id: new_id)
    end
  end
end

app/models/icon.rb
class Icon < ActiveRecord::Base
  belongs_to :user
  belongs_to :template
  has_and_belongs_to_many :galleries

  validates_presence_of :url, :user, :keyword
  validate :url_is_url
  validate :uploaded_url_not_in_use
  nilify_blanks

  before_destroy :delete_from_s3

  def as_json(options={})
    super({only: [:id, :url, :keyword]}.reverse_merge(options))
  end

  def uploaded?
    url.to_s.starts_with?('http://glowfic-constellation.s3.amazonaws.com/')
  end

  def s3_key
    return unless uploaded?
    url[url.index('com/')+4..-1]
  end

  private

  def url_is_url
    return true if url.to_s.starts_with?('http')
    errors.add(:url, "must be an actual fully qualified url (http://www.example.com)")
  end

  def delete_from_s3
    return unless uploaded?
    resp = S3_BUCKET.delete_objects(delete: {objects: [{key: s3_key}], quiet: true})
  end

  def uploaded_url_not_in_use
    return unless uploaded?
    check = Icon.where(url: url)
    check = check.where('id != ?', id) unless new_record?
    return unless check.exists?
    self.url = url_was
    errors.add(:url, 'has already been taken')
  end

  class UploadError < Exception
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_filter :login_required, :except => [:index, :show, :facecasts]
  before_filter :find_character, :only => [:show, :edit, :update, :destroy, :icon]
  before_filter :find_group, :only => :index
  before_filter :require_own_character, :only => [:edit, :update, :destroy, :icon]
  before_filter :build_editor, :only => [:new, :create, :edit, :update]

  def index
    (return if login_required) unless params[:user_id].present?
    @user = current_user
    if params[:user_id]
      @user = User.find_by_id(params[:user_id])
      unless @user
        flash[:error] = "User could not be found."
        redirect_to users_path and return
      end
    end

    @characters = @user.characters.order('name asc')
  end

  def new
    @character = Character.new(template_id: params[:template_id])
  end

  def create
    @character = Character.new((params[:character] || {}).merge(user: current_user))

    if @character.valid?
      save_character_with_extras
      flash[:success] = "Character saved successfully."
      redirect_to character_path(@character)
    else
      flash.now[:error] = "Your character could not be saved."
      render :action => :new
    end
  end

  def show
    @posts = @character.recent_posts(25, page)
  end

  def edit
  end

  def update
    @character.assign_attributes(params[:character])

    if @character.valid?
      save_character_with_extras
      flash[:success] = "Character saved successfully."
      redirect_to character_path(@character)
    else
      flash.now[:error] = "Your character could not be saved."
      render :action => :edit
    end
  end

  def destroy
    @character.destroy
    flash[:success] = "Character deleted successfully."
    redirect_to characters_path
  end

  def icon
    icon = Icon.find_by_id(params[:icon_id])
    @character.update_attributes(default_icon: icon) if icon
    render :json => {}
  end

  def facecasts
    chars = Character.where('pb is not null')
    @pbs = {}

    if params[:sort] == "name"
      chars.each do |character|
        key = character.template || character
        @pbs[key] ||= []
        @pbs[key] << character.pb
      end
    else
      chars.each do |character|
        @pbs[character.pb] ||= []
        @pbs[character.pb] << character unless character.template
        @pbs[character.pb] << character.template if character.template
      end
    end
  end

  private

  def find_character
    @character = Character.find_by_id(params[:id])

    unless @character
      flash[:error] = "Character could not be found."
      redirect_to characters_path and return
    end
  end

  def find_group
    return unless params[:group_id].present?
    @group = CharacterGroup.find_by_id(params[:group_id])
  end

  def require_own_character
    if @character.user_id != current_user.id
      flash[:error] = "That is not your character."
      redirect_to characters_path and return
    end
  end

  def build_editor
    faked = Struct.new(:name, :id)
    new_template = faked.new('— Create New Template —', 0)
    @templates = current_user.templates.order('name asc') + [new_template]
    new_group = faked.new('— Create New Group —', 0)
    @groups = current_user.character_groups.order('name asc') + [new_group]
    use_javascript('characters')
    gon.character_id = @character.try(:id) || ''
  end

  def save_character_with_extras
    Character.transaction do
      if template = @character.instance_variable_get('@template')
        template.save
        @character.template = template
      end
      if group = @character.instance_variable_get('@group')
        group.save
        @character.character_group = group
      end
      @character.save
    end
  end
end

app/views/characters/_editor.haml
%tr
  %th.sub Name
  %td{class: cycle('even', 'odd')}= f.text_field :name, placeholder: "Character Name", class: 'text'
%tr
  %th.sub Nickname
  %td{class: cycle('even', 'odd')}= f.text_field :template_name, placeholder: "Template Nickname", class: 'text'
%tr
  %th.sub Screenname
  %td{class: cycle('even', 'odd')}= f.text_field :screenname, placeholder: "Screen Name", class: 'text'
%tr
  %th.sub Setting
  %td{class: cycle('even', 'odd')}= f.text_field :setting, placeholder: "Setting", class: 'text'
%tr
  - klass = cycle('even', 'odd')
  %th.sub Template
  %td{class: klass}= f.collection_select :template_id, @templates, :id, :name, {include_blank: '— Choose Template —'}, {class: 'text'}
%tr#create_template{class: ('hidden' unless params[:character].try(:[], :template_id) == "0")}
  %th.sub &#8627; Name
  %td{class: klass}= f.text_field :new_template_name, placeholder: "Template Name", class: 'text'
- if current_user.galleries.present?
  %tr
    %th.sub Galleries
    %td{class: cycle('even', 'odd')}
      = f.collection_select(:gallery_ids, 
      current_user.galleries.order('name asc'), 
      :id, :name, {selected: @character.galleries.map(&:id)}, {:class => 'text', multiple: true})
%tr
  %th.sub Facecast
  %td{class: cycle('even', 'odd')}= f.text_field :pb, placeholder: "Facecast", class: 'text'
%tr
  %th.centered.subber{colspan: 2}= submit_tag "Save", class: 'button'

#selected-gallery
  %b Images
  %br 
  Pick Default Icon (Optional):
  %br
  .gallery
    - if @character.galleries.present?
      - @character.galleries.each do |gallery|
        %div{id: "gallery#{gallery.id}", :'data-id' => gallery.id }
          %br
          %b= gallery.name
          %br
          - gallery.icons.order('keyword asc').each do |icon|
            - klass = 'character-icon'
            - klass += ' selected-icon' if icon == @character.default_icon
            = icon_tag icon, class: klass, id: icon.id
    - else
      #gallery0{:'data-id' => 0}
        - current_user.icons.where(has_gallery: false).order('keyword asc').each do |icon|
          - next if icon.galleries.present?
          - klass = 'character-icon'
          - klass += ' selected-icon' if icon == @character.default_icon
          = icon_tag icon, class: klass, id: icon.id

app/views/characters/_icon_view.haml
%tr
  %td.green.left-align
    .gallery
      - @characters.includes(:default_icon).each do |character|
        .gallery-icon
          = link_to character_path(character) do
            - if character.icon
              = icon_tag character.icon
              %br
            - else
              <div class='icon gallery-no-icon'>&nbsp;</div>
              %br
            %span.character-name= character.name
          - if character.user_id == current_user.try(:id)
            .delete-button{ id: character.id }
              = link_to 'X', character_path(character), :method => :delete, confirm: 'Are you sure you want to delete '+character.name+'?'
      - if @characters.empty?
        .centered — No characters yet —

app/views/characters/_list_section.haml
%tr
  %td.beige.padding-10{colspan: 6}
    - if name.is_a? ActiveRecord::Base::Template
      %b
        Template:
        = link_to name.name, template_path(name)
    - else
      %b= name
- if characters.empty?
  %tr
    %td.centered.padding-5{class: cycle('even', 'odd'), colspan: 6} — No characters yet —
- else
  %tr
    - klass = cycle('even', 'odd')
    %td.padding-5{class: klass}
      %b Name
    %td.padding-5{class: klass}
      %b Nickname
    %td.padding-5{class: klass}
      %b Screenname
    %td.padding-5{class: klass}
      %b PB
    %td.padding-5{class: klass}
      %b Setting
    %td.padding-5{class: klass}
  - characters.order('name asc').each do |character|
    - klass = cycle('even', 'odd')
    %tr
      %td.padding-5{class: klass}
        = link_to character.name, character_path(character)
      %td.padding-5{class: klass, style:'width:15%'}= character.template_name
      %td.padding-5{class: klass, style:'width:15%'}= character.screenname
      %td.padding-5{class: klass, style:'width:20%'}= character.pb
      %td.padding-5{class: klass, style:'width:15%'}= character.setting

      %td.width-70.right-align{class: klass}
        - if @user.id == current_user.try(:id)
          = link_to edit_character_path(character) do
            = image_tag "/images/pencil.png"
          = link_to character_path(character), :method => :delete, confirm: 'Are you sure you want to delete '+character.name+'?' do
            = image_tag "/images/cross.png"
          &nbsp;

app/views/characters/_list_view.haml
- if @group
  - @group.characters.map(&:template).uniq.compact.sort_by(&:name).each do |template|
    = render partial: 'characters/list_section', locals: {name: template, characters: template.characters}
  - if @group.characters.where(template_id: nil).exists?
    = render partial: 'characters/list_section', locals: {name: "No Template", characters: @group.characters.where(template_id: nil).order('name asc')}
- elsif @template
  = render partial: 'characters/list_section', locals: {name: @template, characters: @template.characters}
- elsif @user.character_groups.exists?
  - @user.character_groups.order('id asc').each do |group|
    %tr
      %th.subber{colspan: 6}
        Group:
        = group.name
    - group.characters.map(&:template).uniq.compact.sort_by(&:name).each do |template|
      = render partial: 'characters/list_section', locals: {name: template, characters: template.characters}
    - if group.characters.where(template_id: nil).exists?
      = render partial: 'characters/list_section', locals: {name: "No Template", characters: group.characters.where(template_id: nil).order('name asc')}
  - if @user.characters.where(character_group_id: nil).exists?
    %tr
      %th{colspan: 6} Ungrouped Characters
    - @user.characters.where(character_group_id: nil).includes(:template).map(&:template).uniq.compact.sort_by(&:name).each do |template|
      - next if template.characters.where('character_group_id is not null').exists?
      = render partial: 'characters/list_section', locals: {name: template, characters: template.characters}
    = render partial: 'characters/list_section', locals: {name: "No Template", characters: @user.characters.where(character_group_id: nil).where(template_id: nil).order('name asc')}

- elsif @user.characters.exists?
  - @user.templates.order('name asc').each do |template|  
    = render partial: 'characters/list_section', locals: {name: template, characters: template.characters}

  - unless @user.characters.where(template_id: nil).count.zero?
    = render partial: 'characters/list_section', locals: {name: "No Template", characters: @user.characters.where(template_id: nil).order('name asc')}
- else
  %tr
    %td.centered.padding-10{class: cycle('even', 'odd'), colspan: 6} — No characters yet —

app/views/characters/edit.haml
- content_for :breadcrumbs do
  = link_to "Characters", characters_path
  &raquo;
  - if @character.template
    = link_to "Templates", templates_path
    &raquo;
    = link_to @character.template.name, template_path(@character.template)
    &raquo;
  = link_to @character.name, character_path(@character)
  &raquo;
  %b Edit

= form_for @character, url: character_path(@character), method: :put do |f|
  %table.form-table
    %tr
      %th.centered{colspan: 2}= @character.name
    = render partial: 'editor', locals: {f: f}
    

app/views/characters/facecasts.haml
%table
  %tr
    %th{colspan: 4} Facecasts
  %tr
    %th.sub= link_to 'Facecast', url_for(sort: nil)
    %th.sub Type
    %th.sub= link_to 'Name', url_for(sort: 'name')
    %th.sub Writer
  - if params[:sort] == "name"
    - characters = @pbs.keys.sort_by{ |char| char.name }
    - characters.each do |character|
      - pbs = @pbs[character].uniq
      - pbs.each do |pb|
        %tr
          - klass = cycle('even','odd')
          %td.padding-5{class: klass}= pb
          %td.padding-5{class: klass}= character.class
          %td.padding-5{class: klass}
            - if character.is_a? Character
              = link_to character.name, character_path(character)
            - else
              = link_to character.name, template_path(character)
          %td.padding-5{class: klass}= link_to character.user.username, user_path(character.user)
  - else
    - @pbs.keys.sort.each do |pb|
      - characters = @pbs[pb].uniq
      - characters.each do |character|
        %tr
          - klass = cycle('even','odd')
          %td.padding-5{class: klass}= pb
          %td.padding-5{class: klass}= character.class
          %td.padding-5{class: klass}
            - if character.is_a? Character
              = link_to character.name, character_path(character)
            - else
              = link_to character.name, template_path(character)
          %td.padding-5{class: klass}= link_to character.user.username, user_path(character.user)

app/views/characters/index.haml
%table
  %tr
    %th{colspan: 6}
      - if @group
        Character Group:
        = @group.name
      - else
        - if @user.id == current_user.try(:id)
          Your
        - else
          = @user.username + "'s"
        Characters
      - if @user.id == current_user.try(:id)
        = link_to new_character_path(character_group_id: @group.try(:id)) do
          .link-box.green + New Character
      = link_to url_for(view: 'icons') do
        .view-button{class: (:selected unless page_view == 'list')}
          = image_tag '/images/grid.png', class: 'icon-view', alt: ''
          Icons
      = link_to url_for(view: 'list') do
        .view-button{class: (:selected if page_view == 'list')}
          = image_tag '/images/list.png', class: 'list-view', alt: ''
          List
  - if page_view == 'list'
    = render partial: 'list_view'
  - else
    = render partial: 'icon_view'

app/views/characters/new.haml
= form_for @character, url: characters_path, method: :post do |f|
  = f.hidden_field :default_icon_id
  %table.form-table
    %tr
      %th.centered{colspan: 2} New Character
    = render partial: 'editor', locals: {f: f}

app/views/characters/show.haml
- content_for :breadcrumbs do
  - if @character.user_id == current_user.try(:id)
    = link_to "Characters", characters_path
  - else
    = link_to "#{@character.user.username}'s Characters", user_characters_path(@character.user)
  - if @character.template
    &raquo;
    - if @character.user_id == current_user.try(:id)
      = link_to "Templates", templates_path
    - else
      = link_to "#{@character.user.username}'s Templates", user_templates_path(@character.user)
    &raquo;
    = link_to @character.template.name, template_path(@character.template)
  &raquo;
  %b= @character.name

.character-info
  - if @character.icon
    .character-icon
      = link_to icon_path(@character.icon) do
        = icon_tag @character.icon
  - if @character.screenname
    %b.character-screenname= @character.screenname
    %br
  %span.character-name= @character.name
  - if @character.template
    = surround '(', ')' do
      = link_to @character.template.name, template_path(@character.template), class: 'character-template'
  - if @character.template_name
    %br
    = precede 'Nickname: ' do
      %span.character-template-nickname=@character.template_name
  - if @character.pb
    %br
    =precede 'Played by: ' do
      %span.character-pb= @character.pb
  - if logged_in? && current_user.id == @character.user_id
    %br
    = link_to 'Edit character', edit_character_path(@character), class: 'character-edit'
%br
- if @posts.present?
  - content_for :posts_title do 'Recent Threads' end
  = render partial: 'posts/list', locals: {posts: @character.recent_posts.includes(:board, :user, :last_user), path: :character_path}
%br
- if @character.galleries.present?
  %table
    %thead
      %tr
        %th Galleries
    %tbody
      - @character.galleries.includes(:user).each do |gallery|
        = render partial: 'galleries/single', locals: {gallery: gallery, klass: 'subber', skip_forms: true}