config/routes.rb
Rails.application.routes.draw do
  root :to => 'sessions#index'
  match '/login' => 'sessions#create', :as => :login, :via => :post
  match '/logout' => 'sessions#destroy', :as => :logout, :via => :delete

  resources :templates
  resources :password_resets, only: [:new, :create, :show, :update]
  resources :boards do collection { post :mark } end
  resources :reports, only: [:index, :show]
  resources :bugs, only: :create
  resources :messages, except: :edit do
    collection { post :mark }
  end
  resources :replies, except: [:index, :new] do
    member { get :history }
  end
  resources :posts do
    member { get :history }
    collection do
      post :mark
      get :search
      get :owed
      get :unread
    end
  end
  resources :characters do
    member do
      post :icon
    end
    collection { get :facecasts }
  end
  resources :icons, except: [:index, :new, :create] do
    member do
      post :avatar
    end
    collection do
      delete :delete_multiple
    end
  end
  resources :users do
    resources :characters, only: :index
    resources :templates, only: :index
    resources :galleries, only: [:index, :show]
    collection do
      post :username
    end
    member do
      post :character
      put :password
    end
  end
  resources :galleries do
    member do
      get :add
      post :icon
    end
  end
end

app/views/layouts/application.haml
!!!
%html
  %head
    %title= (Rails.env.development? ? 'DEV: ' : '') + (@page_title ? @page_title + " | Glowfic Constellation" : "Glowfic Constellation")
    %meta{ :charset => "utf-8" }
    <meta name="viewport" content="width=device-width">
    = stylesheet_link_tag 'application'
    - if current_user.try(:layout).present?
      = stylesheet_link_tag "layouts/#{current_user.layout}"
    %link{ :href => "/stylesheets/chosen.css", :rel => "stylesheet", :type => "text/css", :media => "screen" }
    <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16.png">
    = csrf_meta_tag
    = include_gon
  %body
    #header
      - if logged_in?
        #user-info
          = link_to user_path(current_user) do
            - if current_user.avatar
              = image_tag current_user.avatar.url, class: 'icon', id: 'user-icon'
              %br
            - else
              .no-img
            #username= current_user.username
      #header-right
        #logo
          = link_to root_path do
            = image_tag '/images/logo.png', alt: 'Glowfic Constellation'
        #nav-top
          - if logged_in?
            %ul
              %li= link_to 'Account', edit_user_path(current_user)
              %li= link_to 'Inbox', messages_path
              %li= link_to "Templates", templates_path
              %li= link_to "Characters", characters_path
              %li= link_to "Galleries", galleries_path
              %li= link_to "Post", new_post_path
            = link_to logout_path, method: :delete, id: :"header-logout" do
              = button_tag "Log out", class: 'button'
          - else
            = form_tag login_path, method: :post do
              #header-forms
                = text_field_tag :username, params[:username], placeholder: "Username"
                = password_field_tag :password, params[:password], placeholder: "Password"
              #header-remember
                = check_box_tag :remember_me
                Remember Me
              #header-buttons
                = submit_tag "Log in", class: 'button'
                = link_to "Sign up", new_user_path
                &nbsp;|&nbsp;
                = link_to "Forgot Password?", new_password_reset_path
      #header-collapse
      #nav-bottom
        %ul
          %li= link_to 'Boards', boards_path
          %li= link_to 'Recently Updated', posts_path
          %li= link_to 'Search', search_posts_path
          %li= link_to 'Glowficcers', users_path
          %li= link_to 'Facecasts', facecasts_characters_path
          - if logged_in?
            %li= link_to 'Unread', unread_posts_path
            %li= link_to 'Tags Owed', owed_posts_path
    - if content_for?(:breadcrumbs)
      .flash.subber= content_for :breadcrumbs
    - if flash[:error].is_a?(Hash)
      .flash.error
        = flash[:error][:message]
        %ul
          - flash[:error][:array].each do |error|
            %li= error
      - flash.delete(:error)
    - flash.keys.each do |key|
      .flash{:class=>key}= flash[key]
    - if logged_in?
      - messages = current_user.messages.select(&:unread?)
      - if messages.present?
        - messages.each do |message|
          .flash.inbox
            New message from
            = link_to message.sender.username, user_path(message.sender)
            &nbsp;- &nbsp;
            = link_to message.subject, message_path(message)
    #content= yield

  = javascript_include_tag 'application'
  - (@javascripts || []).each do |javascript|
    = javascript_include_tag javascript